config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'landing_page#index'

  # Static pages
  get 'pricing', to: 'static_pages#pricing'
  get 'features', to: 'static_pages#features'
  get 'contact_us', to: 'static_pages#contact_us'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'customer_agreement', to: 'static_pages#customer_agreement'
  get 'security', to: 'static_pages#security'
  get 'jobs', to: 'static_pages#jobs'
  get 'how', to: 'static_pages#how'

  # frontend app
  get 'frontend_events', to: 'frontend_events#index'
  get 'q', to: 'frontend_events#show'
  resources :questions, only: [:create, :edit, :update, :destroy] do
    member do
      put 'upvote', to: 'questions#upvote'
      put 'downvote', to: 'questions#downvote'
    end
  end

  authenticate :user do
    resources :events do
    	member do
        get :settings
    		patch :start_now
    		patch :end_now
  		end
		end
  end

  post 'api_questions', to: 'api/questions#create'
  patch 'vote_question', to: 'api/questions#vote'
  delete 'delete_question', to: 'api/questions#delete'
end

app/models/event.rb
class Event < ApplicationRecord
  include ActionView::Helpers::DateHelper

  belongs_to :user
  has_many :questions
  scope :finito, -> { where("ends_at < ?", Time.zone.now) }
  scope :active, -> { where('ends_at > ?', Time.zone.now) }
  extend FriendlyId
  friendly_id :password, use: :slugged

  validates :title, :password, :starts_at, :ends_at, :user, :time_zone, presence: true
  validates :title, length: { maximum: 30 }
  validates :description, length: { maximum: 2000 }
  validates :password, uniqueness: true
  validate :starts_at_cannot_be_in_the_past
  validate :ends_at_can_not_be_before_starts_at

  default_scope { order(created_at: :desc) }

  before_validation :set_password, on: :create
  before_validation :set_default_start_end_time_zone, on: :create
  after_create :add_slug

  def active?
    ends_at > Time.zone.now
  end

  def status
    if starts_at > Time.now && ends_at > Time.now
      "not started"
    elsif starts_at < Time.now && ends_at > Time.now
      "live"
    elsif starts_at < Time.now && ends_at < Time.now
      "finished"
    else
      'ERROR'
    end
  end

  def status_2
    if status == 'not started'
      "starts in #{distance_of_time_in_words(Time.now, starts_at)}"
    elsif status == 'live'
      "ends in #{distance_of_time_in_words(Time.now, ends_at)}"
    elsif status == 'finished'
      nil
    else
      'ERROR'
    end
  end

  def vote_quantity
    questions.map(&:weighted_score).sum
  end

  private

  def add_slug
    self.update_attributes!(slug: password)
  end

  def set_password
    self.password = generate_token
  end

  def set_default_start_end_time_zone
    self.starts_at = Time.zone.now + 1.hour
    self.ends_at = Time.zone.now + 2.hours
    self.time_zone = user.time_zone
  end

  def generate_token
    loop do
      #token = SecureRandom.hex(6)
      token = rand(999999)
      break token unless Event.where(password: token).exists?
    end
  end

  def starts_at_cannot_be_in_the_past
    if starts_at.present? && starts_at <= Time.now
      errors.add(:starts_at, "- You can not start an event in the past")
    end
  end

  def ends_at_can_not_be_before_starts_at
    if ends_at.present? && ends_at <= starts_at
      errors.add(:ends_at, "- Event can not end before it starts")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :start_now, :end_now, :settings]

  def start_now
		@event.update_attribute(:starts_at, Time.now)
		redirect_to @event, notice: "Q&A started. Questions and votes can be added."
	end

  def end_now
		@event.update_attribute(:ends_at, Time.now)
		redirect_to @event, notice: "Q&A finished. No more questions and votes."
	end

  def index
    #@events = Event.where(user: current_user)
    @q = Event.where(user: current_user).ransack(params[:q])
    @events = @q.result(distinct: true)
  end

  def settings
    unless @event.user_id == current_user.id
      redirect_to @event
    end
  end

  def show
    @question = Question.new
    @questions = @event.questions
    #@questions = @event.questions.order(:cached_weighted_score => :desc)
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = 'Successfully created'
      redirect_to event_path(@event)
    else
      flash_errors
      render :new
    end
  end

  def update
    if @event.update(event_params)
      @events = Event.where(user: current_user)
      flash[:success] = 'Successfully updated'
      redirect_to event_path(@event)
    else
      flash_errors
      render :edit
    end
  end

  def destroy
    @event.destroy
    @events = Event.all
    flash[:success] = 'Event was successfully deleted'
    redirect_to events_path
  end

  private

  def flash_errors
    errors = @event.errors.full_messages.join(', ')
    flash[:error] = errors
  end

  def set_event
    @event = Event.friendly.find(params[:id])
  end

  def event_params
    params[:event].permit(:title, :description, :starts_at, :ends_at, :user,
                          :company_name, :country, :time_zone, :password,
                          :user_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def status_label(status)
		status_span_generator(status)			
	end

	private
		def status_span_generator(status)
			case status
			when 'not started'
				content_tag(:span, status.titleize, class: 'badge badge-info')
			when 'live'
				content_tag(:span, status.titleize, class: 'badge badge-success')
			when 'finished'
				content_tag(:span, status.titleize, class: 'badge badge-secondary')
			when 'ERROR'
				content_tag(:span, status.titleize, class: 'badge badge-danger')
			end
  end
end

app/views/events/_event_admin.haml
%p
.row
.card-group
  .row
    .col
      .card.border-warning
        .card-header.bg-warning.text-center
          %b Manage event
        .card-body
          %small
            Participants can ask questions and vote in this time period:
            %br
            = "Start: #{@event.starts_at.strftime('%d-%b %Y, %H:%M')}"
            %br
            = "End: #{@event.ends_at.strftime('%d-%b %Y, %H:%M')}"
            (#{distance_of_time_in_words @event.ends_at, @event.starts_at})
            %br
            = "Time zone: #{@event.time_zone}"
            = link_to 'Edit time', edit_event_path(@event), class: 'btn btn-primary btn-sm btn-block'
            %hr
            .text-center
              %h5
                Status:
                = status_label(@event.status)
              - if @event.starts_at > Time.now
                starts in
                = distance_of_time_in_words Time.now, @event.starts_at
                = button_to "Start now", start_now_event_path(@event), method: :patch
              - if @event.status == 'active'
                = button_to "End now", end_now_event_path(@event), method: :patch
    .col
      .card.border-warning
        .card-header.bg-warning.text-center
          %b Engage attendees
        .card-body
          %small
            = link_to '1. Show attendees how to join', event_path, class: 'btn btn-outline-success btn-block'
            %p 
              Tell attendees to submit their questions now by going to www.askdemos.com with the passcode 
              %b #{@event.password}.
            = link_to '2. Show question board on screen', event_path, class: 'btn btn-outline-success btn-block'
            %p New questions automatically appear on the Projector Panel.
    .col
      .card.border-warning
        .card-header.bg-warning.text-center
          %b Customize
        .card-body
          %small
            = link_to 'Logo branding', event_path, class: 'btn btn-outline-success btn-block'
            %p Give your brand more visibility by adding your company or event logo on the Projector Panel.
            = link_to 'Custom branding', event_path, class: 'btn btn-outline-success btn-block'
            %p Ensure that the look and feel of AskDemos meets your company or event's branding.
            = link_to 'Add speaker/event details', event_path, class: 'btn btn-outline-success btn-block'
            %p Ensure that the look and feel of AskDemos meets your company or event's branding.
    .col
      .card.border-warning
        .card-header.bg-warning.text-center
          %b Insights
        .card-body.text-center
          .btn.btn-info.btn-block
            .fa.fa-users
            participants
          .btn.btn-info.btn-block
            .fa.fa-question
            /= fa_icon "impressions"
            = pluralize(@event.questions.count, 'question')
          .btn.btn-info.btn-block
            .fa.fa-thumbs-up
            = pluralize(@event.vote_quantity, 'vote')
          = link_to 'Excel Download', event_path, class: 'btn btn-outline-success btn-block'

app/views/events/_form.haml
= form_for @event, html: {class: 'form-horizontal'} do |f|
  = f.hidden_field(:user_id, value: current_user.id)
  .form-group.row
    = f.label 'Title: *', class: 'col-md-3 col-form-label'
    .col-md-9
      = f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Event name'
  - if f.object.new_record?
    .form-group.row
      .col-md-3.col-form-label
      .col-md-9.col-form-label
        .pull-left
          %button.btn.btn-primary{"data-target" => "#accordion", "data-toggle" => "collapse", :type => "button"}
            .fa.fa-cog
            More options
    #accordion.collapse
      .form-group.row
        = f.label 'Description:', class: 'col-md-3 col-form-label'
        .col-md-9
          = f.text_field :description, class: 'form-control', placeholder: 'Any additional info you want the participants to know'
      .form-group.row
        .col-md-3.col-form-label
        .col-md-9.col-form-label
          .text-left
            Participants can ask questions and vote in this time period:
      .form-group.row
        = f.label 'Starts at:', class: 'col-md-3 col-form-label'
        .col-md-9
          /= f.datetime_select :starts_at, minute_step: 15, :default => Time.zone.now + 1.hour
          = f.datetime_select :starts_at, :default => Time.zone.now + 5.minutes
      .form-group.row
        = f.label 'Ends at:', class: 'col-md-3 col-form-label'
        .col-md-9
          = f.datetime_select :ends_at, :default => Time.zone.now + 65.minutes
          /= f.date_field :ends_at, value: @event.ends_at || (Time.now + 10.days).strftime('%Y-%m-%d'), class: "form-control"
      .form-group.row
        = f.label 'Time zone:', class: 'col-md-3 col-form-label'
        .col-md-9
          = f.time_zone_select(:time_zone, nil, {}, { class: 'custom-select' })
  - else
    .form-group.row
      = f.label 'Description:', class: 'col-md-3 col-form-label'
      .col-md-9
        = f.text_field :description, class: 'form-control', placeholder: 'Any additional info you want the participants to know'
    .form-group.row
      .col-md-3.col-form-label
      .col-md-9.col-form-label
        .text-left
          Participants can ask questions and vote in this time period:
    .form-group.row
      = f.label 'Starts at:', class: 'col-md-3 col-form-label'
      .col-md-9
        /= f.datetime_select :starts_at, minute_step: 15, :default => Time.zone.now + 1.hour
        = f.datetime_select :starts_at, :default => Time.zone.now + 5.minutes
    .form-group.row
      = f.label 'Ends at:', class: 'col-md-3 col-form-label'
      .col-md-9
        = f.datetime_select :ends_at, :default => Time.zone.now + 65.minutes
        /= f.date_field :ends_at, value: @event.ends_at || (Time.now + 10.days).strftime('%Y-%m-%d'), class: "form-control"
    .form-group.row
      = f.label 'Time zone:', class: 'col-md-3 col-form-label'
      .col-md-9
        = f.time_zone_select(:time_zone, nil, {}, { class: 'custom-select' })
  .form-group.row
    .col-md-3
    .col-md-9
      = f.submit 'Create Event', class: 'btn btn-lg btn-warning'
      /= f.button :submit, class: 'btn btn-warning'
  .links
    - unless f.object.new_record?
      = link_to 'Back', event_path(@event), class: 'btn btn-secondary'
    - else
      = link_to 'Back', events_path, class: 'btn btn-secondary'

app/views/events/edit.haml
- content_for :title do
  = @event.title
  | Edit
= render 'shared/flash_messages' if flash.any?

.row.event-container
  .col-md-2
  .col-md-8
    .card
      %h2.card-header.bg-warning
        Edit Event
      .card-body
        = render 'form'

app/views/events/index.haml
= render 'shared/flash_messages' if flash.any?
%h1.display-4 My Events
.form-inline
  .badge.badge-secondary
    %h5
      = pluralize(current_user.events.count, 'Event')
  .mr-sm-2
  = link_to 'Create Q&A event', new_event_path, class: 'btn btn-primary'
  .mr-sm-2
  = link_to 'Upgrade plan', events_path, class: 'btn btn-danger disabled'
%p
.text-white
%p
- if current_user.events.any?
  %table.table.table-responsive.table-hover.bg-white
    %thead.bg-warning
      %tr
        /%th
        /  = link_to "<i class='fa fa-refresh'></i>".html_safe, events_path, class: 'btn btn-outline-secondary'
        %th
          %form.form-inline.my-2.my-lg-0
            = search_form_for @q, url: events_path do |f|
              .mr-sm-2
                = f.text_field :title_cont, class: 'form-control', placeholder: 'Find Event', autofocus: true
        /%th Description
        /%th Password
        %th= sort_link(@q, :starts_at, "Starts")
        %th= sort_link(@q, :ends_at, "Ends")
        %th Status
        %th Duration
        %th= sort_link(@q, :created_at, "Created")
        %th= sort_link(@q, :updated_at, "Updated")
        %th{:scope => 'col', :colspan => '2'} Actions
    %tbody
      - @events.each do |event|
        %tr
          /%td
          /  .badge.badge-secondary.btn-block
          /    .fa.fa-users
          /    participants
          /  %br
          /  .badge.badge-secondary.btn-block
          /    .fa.fa-question
          /    /= fa_icon "impressions"
          /    = pluralize(event.questions.count, 'question')
          /  %br
          /  .badge.badge-secondary.btn-block
          /    .fa.fa-thumbs-up
          /    = pluralize(event.vote_quantity, 'vote')
          %td= link_to event.title, event, class: 'btn btn-outline-primary btn-block'
          /%td= simple_format(event.description)
          /%td
          /  %b= event.password.upcase
          /%td= event.starts_at.strftime('%e %b %Y, %H:%M (%z)')
          %td= event.starts_at.strftime('%e %b %Y, %H:%M')
          %td= event.ends_at.strftime('%e %b %Y, %H:%M')
          %td
            = status_label(event.status)
            %p= event.status_2
            /- if event.starts_at > Time.now
            /  %br
            /  = event.status_2
            /  = button_to "Start now", start_now_event_path(event), method: :patch
            /- if event.status == 'live'
            /  = button_to "End now", end_now_event_path(event), method: :patch
          %td= distance_of_time_in_words event.ends_at, event.starts_at
          %td
            = "#{time_ago_in_words(event.created_at)} ago"
            /by #{event.user.username}"
          %td= "#{time_ago_in_words(event.updated_at)} ago"
          %td
            /= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
            /= link_to '', edit_event_path(event), class: "btn btn-success fa fa-pencil btn-xs", title: 'Show Client', 'data-toggle' => 'tooltip', 'data-placement' => 'top'
            = link_to settings_event_path(event) do
              .btn.btn-outline-secondary.btn-block.btn-sm
                .fa.fa-cog
                Settings
          %td
            = link_to event, method: :delete, data: { confirm: 'Are you sure?' } do 
              .btn.btn-outline-secondary.btn-block.btn-sm
                .fa.fa-trash
                Destroy
%br

app/views/events/new.haml
= render 'shared/flash_messages' if flash.any?

.row.event-container
  .col-md-2
  .col-md-8
    .card
      %h2.card-header.bg-warning
        Create Event
      .card-body
        = render 'form'

app/views/events/settings.haml
- content_for :title do
  = @event.title
  | Settings
%br
.card.bg-warning
  = link_to event_path(@event), class: 'btn btn-block btn-warning' do
    %h2
      .pull-left
        = "#{@event.title}"
      .pull-right
        Password: #{@event.password}
%br
.row
  /.col-lg-3
  /  .card
  /    .card-header.text-center
  /      %b Manage event
  /    .card-body
  /      %b Title:
  /      = @event.title
  /      %p
  /      %b Description:
  /      = @event.description
  /      %p
  /      %b Password:
  /      = @event.password
  /      %p
  /      %b Starts at:
  /      = @event.starts_at
  /      %p
  /      %b Ends at:
  /      = @event.ends_at
  /      %p
  /      %b Time zone:
  /      = @event.time_zone
  .col-lg-3
    .card
      .card-header.text-center
        %b 1. Manage event
      .card-body
        .text-center
          Status:
          = status_label(@event.status)
          %p= @event.status_2
          - if @event.starts_at > Time.now
            = button_to "Start now", start_now_event_path(@event), method: :patch, class: 'btn btn-success btn-block'
          - if @event.status == 'live'
            = button_to "End now", end_now_event_path(@event), method: :patch, class: 'btn btn-danger btn-block'
        %hr
        - unless @event.status == 'finished'
          = link_to 'Edit time & description', edit_event_path(@event), class: 'btn btn-primary btn-block'
        %small
          Participants can ask questions and vote in this time period:
        .text-center
          = "Start: #{@event.starts_at.strftime('%d-%b %Y, %H:%M')}"
          %br
          = "End: #{@event.ends_at.strftime('%d-%b %Y, %H:%M')}"
          /(#{distance_of_time_in_words @event.ends_at, @event.starts_at})
          %br
          = "Time zone: #{@event.time_zone}"

  .col-lg-3
    .card
      .card-header.text-center
        %b 2. Customize
      .card-body
        - unless @event.status == 'finished'
          %small
            = link_to 'Logo branding', event_path, class: 'btn btn-danger btn-block disabled'
            %p Give your brand more visibility by adding your company or event logo on the Projector Panel.
            %hr
            = link_to 'Custom branding', event_path, class: 'btn btn-danger btn-block disabled'
            %p Ensure that the look and feel of AskDemos meets your company or event's branding.
            %hr
            = link_to 'Add speaker/event details', event_path, class: 'btn btn-danger btn-block disabled'
            %p Ensure that the look and feel of AskDemos meets your company or event's branding.
        - else
          .text-center
            = status_label(@event.status)
  .col-lg-3
    .card
      .card-header.text-center
        %b 3. Engage attendees
      .card-body
        - unless @event.status == 'finished'
          %small
            = link_to '1. Show attendees how to join', event_path, class: 'btn btn-primary btn-block'
            %p 
              Tell attendees to submit their questions now by going to www.askdemos.com with the password
              %b #{@event.password}.
            %hr
            = link_to '2. Show question board on screen', event_path, class: 'btn btn-primary btn-block'
            %p New questions automatically appear on the Projector Panel.
        - else
          .text-center
            = status_label(@event.status)
          %hr
          = link_to 'View Q&A board', event_path, class: 'btn btn-primary btn-block'
  .col-lg-3
    .card
      .card-header.text-center
        %b 4. Insights
      .card-body.text-center
        %h5
          .badge.badge-secondary.btn-block
            .fa.fa-users
            participants
          .badge.badge-secondary.btn-block
            .fa.fa-question
            /= fa_icon "impressions"
            = pluralize(@event.questions.count, 'question')
          .badge.badge-secondary.btn-block
            .fa.fa-thumbs-up
            = pluralize(@event.vote_quantity, 'vote')
        %hr
        = link_to 'Excel Download', event_path, class: 'btn btn-danger btn-block disabled'
        %small
          %p Detailed audience engagement report.

app/views/events/show.haml
- content_for :title do
  = @event.title
= render 'shared/flash_messages' if flash.any?
.row
  .col-lg-2
  .col-lg-8
    .event-container
      .card.border-warning
        %h2.card-header.bg-warning
          = "#{@event.title}"
          - if current_user && @event.user_id == current_user.id
            .pull-right
              = status_label(@event.status)
              = link_to settings_event_path, class: 'btn btn-warning' do
                .fa.fa-cog{:style => "font-size:25px"}
        - if @event.description?
          .card-header.bg-warning
            %small
              = "#{@event.description}"
        .card-header.bg-warning
          - if @event.status == 'live'
            = form_for @question do |f|
              = f.hidden_field(:event_id, value: @event.id)
              = f.hidden_field(:user_id, value: current_user&.id)
              .form-group
                /= f.text_area :contents, autofocus: true, class: 'form-control', placeholder: "Enter your question here"
                = f.text_area :contents, autofocus: true, class: 'form-control', placeholder: "Do you have a new question?"
                = f.submit 'Ask', class: 'btn btn-info add-question-submit'
          - elsif @event.status == 'not started'
            .text-center
              Q&A session 
              = status_label(@event.status)
              \.
              #{@event.status_2}
          - else
            .text-center
              Q&A session 
              = status_label(@event.status)
              \.
              Thank you for participating!
      - if @event.questions.any?
        %p
        - @questions.each do |question|
          .card
            .card-body
              .row
                .col-lg-auto
                  - unless @event.status == 'finished'
                    - unless current_user.voted_for? question
                      = link_to upvote_question_path(question), method: :put do
                        .col-md-12
                          /.btn.btn-outline-success
                          /  %i.fa.fa-thumbs-up{:style => "font-size:30px;color:orange;"}
                          %i.fa.custom-fa.fa-thumbs-up{:style => "font-size:25px;color:transparent"}
                    - else
                      .col-md-12
                        %i.fa.fa-thumbs-up{:style => "font-size:25px;color:orange"}
                  - else
                    .col-md-12
                      %i.fa.fa-thumbs-up{:style => "font-size:25px;color:grey"}
                  %span= pluralize(question.weighted_score, 'vote')
                .col-lg
                  = question.contents
                  /= simple_format(question.contents)
%br
/.card-body.questions-container
/  - if @event.questions.any?
/    %h1 Questions:
/    - @event.questions.each do |question|
/      .question
/        .contents
/          %h4= question.contents
/        .author
/          asked by:
/          = email = question&.user&.email
/        - if email.present? && email.eql?(question&.user&.email)
/          = link_to 'Edit', edit_question_path(question), class: 'btn btn-primary'
/          = link_to 'Delete', question_path(question), method: :delete,
/            data: { confirm: 'Are you sure?'}, class: 'btn btn-danger'
/        .votes
/          .row
/            .col-md-1{style: "font-size: 30px; color:#606060; text-align: center;"}
/              = link_to upvote_question_path(question), method: :put do
/                %i.fa.fa-caret-up.col-md-12