config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'landing_page#index'

  # Static pages
  get 'pricing', to: 'static_pages#pricing'
  get 'features', to: 'static_pages#features'
  get 'contact_us', to: 'static_pages#contact_us'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'customer_agreement', to: 'static_pages#customer_agreement'
  get 'security', to: 'static_pages#security'
  get 'jobs', to: 'static_pages#jobs'
  get 'how', to: 'static_pages#how'

  # frontend app
  get 'frontend_events', to: 'frontend_events#index'
  get 'q', to: 'frontend_events#show'
  resources :questions, only: [:create, :edit, :update, :destroy] do
    member do
      put 'upvote', to: 'questions#upvote'
      put 'downvote', to: 'questions#downvote'
    end
  end

  authenticate :user do
    resources :events do
    	member do
        get :settings
    		patch :start_now
    		patch :end_now
  		end
		end
  end

  post 'api_questions', to: 'api/questions#create'
  patch 'vote_question', to: 'api/questions#vote'
  delete 'delete_question', to: 'api/questions#delete'
end

app/views/layouts/_footer.haml
%footer.page-footer.font-small.stylish-color-dark.pt-4.mt-4
.bg-dark.text-white
  -  unless current_user
    %hr.bg-light
    / Call to action
    %ul.list-unstyled.list-inline.text-center.py-2
      %li.list-inline-item
        %h5.mb-1 Ready to get started?
      = link_to 'Get started for free', new_user_registration_path, class: 'btn btn-lg btn-warning'

    / Call to action
    %hr/
    / Footer Links
    .container.text-center.text-md-left
      / Grid row
      .row
        / Grid column
        .col-md-4.mx-auto
          / Content
          %h5.font-weight-bold.text-uppercase.mt-3.mb-4
            /Footer Content
          %p
            %small
              %br
              © #{Time.now.year} Copyright - Askdemos Ltd. 
              %br
              All rights reserved -
              %a{:href => "http://www.askdemos.com/"} askdemos.com
              %br
              13 Konstruktorska str. 02-651, Warsaw, Poland
              %br
              = mail_to 'hello@askdemos.com'
              %hr.bg-light
              / Social buttons
              %li.list-inline-item
                = link_to "https://www.instagram.com/askdemos/", target: :_blank do
                  %i.fa.fa-instagram{:style => "font-size:25px;color:white"}
              %li.list-inline-item
                = link_to "https://www.youtube.com/channel/UCrksy4sc0LqLP3aHSbcbLeQ/featured", target: :_blank do
                  %i.fa.fa-youtube{:style => "font-size:25px;color:white"}
              %li.list-inline-item
                = link_to "https://twitter.com/askdemos/", target: :_blank do
                  %i.fa.fa-twitter{:style => "font-size:25px;color:white"}
              %li.list-inline-item
                = link_to "https://www.linkedin.com/company/askdemos/", target: :_blank do
                  %i.fa.fa-linkedin{:style => "font-size:25px;color:white"}
        / Grid column
        %hr.clearfix.w-100.d-md-none/
        / Grid column
        .col-md-2.mx-auto
          / Links
          %h5.font-weight-bold.text-uppercase.mt-3.mb-4 Product
          %ul.list-unstyled
            = link_to 'Features', features_path
            %br
            = link_to 'How?', how_path
            %br
            = link_to 'Pricing', pricing_path
        / Grid column
        %hr.clearfix.w-100.d-md-none/
        / Grid column
        .col-md-2.mx-auto
          / Links
          %h5.font-weight-bold.text-uppercase.mt-3.mb-4 Legal
          %ul.list-unstyled
            = link_to 'Pricing policy', privacy_policy_path
            = link_to 'Customer agreement', customer_agreement_path
            = link_to 'Terms of service', terms_of_service_path
            = link_to 'Security', security_path
        / Grid column
        %hr.clearfix.w-100.d-md-none/
        / Grid column
        .col-md-2.mx-auto
          / Links
          %h5.font-weight-bold.text-uppercase.mt-3.mb-4 About us
          %ul.list-unstyled
            = link_to 'Contact us', contact_us_path
            %br
            = link_to 'Jobs', jobs_path
        / Grid column
      / Grid row
    / Footer Links
  - else
    .text-center
      = link_to 'Privacy policy', privacy_policy_path
      and
      = link_to 'Customer agreement', customer_agreement_path
      %br
      Powered by
      = image_tag "askdemos-logo-1.png", size: "25x25", class: "mx-auto d-inline align-top", :alt => "avatar"
      Askdemos Q&A

app/views/layouts/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-warning.justify-content-between
  = form_tag 'q', enforce_utf8: false, method: :get, class: 'form-inline my-2 my-lg-0' do
    .form-group
      = text_field_tag :password, nil, class: 'form-control mr-sm-2', placeholder: 'Enter Event Code'
      = submit_tag 'Find', class: 'btn', name: nil
    /%button.btn.btn-outline-dark.my-2.my-sm-0{:type => "submit"} Join!
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.sticky-top
  %a.navbar-brand{:href => "/"}
    = image_tag "askdemos-logo-1-black.png", size: "25x25", class: "mx-auto d-inline align-top", :alt => "avatar"
    Askdemos
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span
      /YA
      .navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - unless current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to 'How', how_path, class: 'nav-link text-white'
        %li.nav-item
          = link_to 'Features', features_path, class: 'nav-link text-white'
        %li.nav-item
          = link_to 'Pricing', pricing_path, class: 'nav-link text-white'
    %ul.navbar-nav.ml-auto
      - unless current_user
        %btn.btn-active.btn-warning
          %li.nav-item
            = link_to 'Sign Up', new_user_registration_path, class: 'nav-link text-dark'
        %li.nav-item
          = link_to 'Log In', new_user_session_path, class: 'nav-link text-white'
      - else
        .form-inline
          = link_to 'My Events', events_path, class: 'btn btn-warning'
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle.text-white{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            = current_user.username
            - if current_user.company_name?
              \|
              = current_user.company_name
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            .dropdown-item
              = link_to 'My events', events_path, class: 'nav-link text-dark'
            .dropdown-item
              = link_to 'Settings', edit_user_registration_path, class: 'nav-link text-dark'
            .dropdown-item
              = link_to 'Billing', root_path, class: 'nav-link text-dark'
            %hr
            .dropdown-item
              = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link text-dark'

app/views/layouts/_user_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand.text-white{:href => "/events"}
    = image_tag "askdemos-logo-1.png", size: "25x25", class: "mx-auto d-inline align-top", :alt => "avatar"
    Askdemos Q&A
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span
      /YA
      .navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto
      /%li.nav-item
      /  = link_to 'My Events', events_path, class: 'nav-link text-white'
      = link_to 'My Events', events_path, class: 'btn btn-warning'
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle.text-white{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          = current_user.username
          \|
          = current_user.company_name
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          .dropdown-item
            = link_to 'My events', events_path, class: 'nav-link text-dark'
          .dropdown-item
            = link_to 'Settings', edit_user_registration_path, class: 'nav-link text-dark'
          .dropdown-item
            = link_to 'Billing', root_path, class: 'nav-link text-dark'
          %hr
          .dropdown-item
            = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link text-dark'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title
      = content_for?(:title) ? yield(:title) : "Q&A at events - Askdemos"
    = favicon_link_tag 'askdemos-logo-1-black.png'
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "Askdemos"}", :name => "description"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = javascript_pack_tag 'event-app-bundle'
    = stylesheet_pack_tag 'event-app-bundle'
  %body.bg-light
    = render 'layouts/navbar'
    .container-fluid
      /= current_user.time_zone
      /= Time.zone.now
      = yield
    = render 'layouts/footer'